### ISSUE TITLE
Allow using Diesel migrations with SQLite 

### ISSUE THREAD

**Issue by otavio** [rust-db/barrel#59]
Hello; the project is very appealing and I'd like to use it to boostrap our database but it seems it cannot be used with Diesel with other backend. Am I wrong?

**Comment by spacekookie** [comment]
Hey there!

I haven't *tried* using Diesel + barrel with SQLite before. But it should generally work. I guess you're referring to the diesel guide which mentions that barrel only supports postgres? That is outdated and we should probably change.

If you follow that guide and just select `sqlite3` as a feature instead of `postgres`, it should work.

But don't hesitate to ping me with problems if you encounter any, as I said: haven't actually used diesel+sqlite yet :sweat_smile:

**Comment by otavio** [comment]
The reason I consider it is not going to work is because of https://github.com/rust-db/barrel/blob/master/src/integrations/diesel.rs#L133; am I missing something?

**Comment by spacekookie** [comment]
Ah woops. No, nevermind. You're not missing something. I forgot that was there :grimacing: 

I'll take a better look tomorrow!
